runtime: python
env: flex

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3
    
manual_scaling:
  instances: 1
  
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 16
  
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
    
readiness_check:
    check_interval_sec: 5
    timeout_sec: 4
    failure_threshold: 2
    success_threshold: 2
    app_start_timeout_sec: 450